# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(962, 733)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 150, app.primaryScreen().size().width(), 591))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalFrame_5 = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame_5.sizePolicy().hasHeightForWidth())
        self.verticalFrame_5.setSizePolicy(sizePolicy)
        self.verticalFrame_5.setMinimumSize(QtCore.QSize(100, 0))
        self.verticalFrame_5.setStyleSheet("background-color:white;")
        self.verticalFrame_5.setObjectName("verticalFrame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalFrame_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4.addWidget(self.verticalFrame_5)
        self.verticalGroupBox_4 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox_4.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox_4.setSizePolicy(sizePolicy)
        self.verticalGroupBox_4.setObjectName("verticalGroupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalGroupBox_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4.addWidget(self.verticalGroupBox_4)
        self.verticalFrame_3 = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame_3.sizePolicy().hasHeightForWidth())
        self.verticalFrame_3.setSizePolicy(sizePolicy)
        self.verticalFrame_3.setMinimumSize(QtCore.QSize(100, 0))
        self.verticalFrame_3.setStyleSheet("background-color: white;")
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4.addWidget(self.verticalFrame_3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -20, 971, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("")
        self.label.setLineWidth(0)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("top.jpg"))
        self.label.setScaledContents(True)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 100, 971, 57))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("background-color:#00283a;\n"
"border: 1px solid black;\n"
"color: orange;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("background-color:#00283a;\n"
"border: 1px solid black;\n"
"color: orange;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gpuBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gpuBtn.sizePolicy().hasHeightForWidth())
        self.gpuBtn.setSizePolicy(sizePolicy)
        self.gpuBtn.setStyleSheet("background-color:#00283a;\n"
"border: 1px solid black;\n"
"color: orange;\n"
"")
        self.gpuBtn.setObjectName("gpuBtn")
        self.horizontalLayout.addWidget(self.gpuBtn)
        self.memBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memBtn.sizePolicy().hasHeightForWidth())
        self.memBtn.setSizePolicy(sizePolicy)
        self.memBtn.setStyleSheet("background-color:#00283a;\n"
"border: 1px solid black;\n"
"color: orange;\n"
"")
        self.memBtn.setFlat(False)
        self.memBtn.setObjectName("memBtn")
        self.horizontalLayout.addWidget(self.memBtn)
        self.moboBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moboBtn.sizePolicy().hasHeightForWidth())
        self.moboBtn.setSizePolicy(sizePolicy)
        self.moboBtn.setStyleSheet("background-color:#00283a;\n"
"border: 1px solid black;\n"
"color: orange;\n"
"")
        self.moboBtn.setObjectName("moboBtn")
        self.horizontalLayout.addWidget(self.moboBtn)
        self.caseBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caseBtn.sizePolicy().hasHeightForWidth())
        self.caseBtn.setSizePolicy(sizePolicy)
        self.caseBtn.setStyleSheet("background-color:#00283a;\n"
"border: 1px solid black;\n"
"color: orange;\n"
"")
        self.caseBtn.setFlat(False)
        self.caseBtn.setObjectName("caseBtn")
        self.horizontalLayout.addWidget(self.caseBtn)
        self.miscBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.miscBtn.sizePolicy().hasHeightForWidth())
        self.miscBtn.setSizePolicy(sizePolicy)
        self.miscBtn.setMinimumSize(QtCore.QSize(0, 55))
        self.miscBtn.setStyleSheet("background-color:#00283a;\n"
"border: 1px solid black;\n"
"color: orange;\n"
"")
        self.miscBtn.setFlat(False)
        self.miscBtn.setObjectName("miscBtn")
        self.horizontalLayout.addWidget(self.miscBtn)
        self.forumsBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forumsBtn.sizePolicy().hasHeightForWidth())
        self.forumsBtn.setSizePolicy(sizePolicy)
        self.forumsBtn.setStyleSheet("background-color:#00283a;\n"
"border: 1px solid black;\n"
"color: orange;\n"
"")
        self.forumsBtn.setFlat(False)
        self.forumsBtn.setObjectName("forumsBtn")
        self.horizontalLayout.addWidget(self.forumsBtn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Pre-Built"))
        self.pushButton.setText(_translate("MainWindow", "CPU"))
        self.gpuBtn.setText(_translate("MainWindow", "GPU"))
        self.memBtn.setText(_translate("MainWindow", "Memory"))
        self.moboBtn.setText(_translate("MainWindow", "Motherboards"))
        self.caseBtn.setText(_translate("MainWindow", "Cases"))
        self.miscBtn.setText(_translate("MainWindow", "Miscellaneous"))
        self.forumsBtn.setText(_translate("MainWindow", "Forums"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
